defaults:
  - dataset: navsim_drivor_cameras
  - model/backbone: deit
  - model/translator: lconv
  - training: frame_level
  - logging: default
  - _self_

seed: 0

model:
  backbone:
    image_size: [672, 1148]
