return_metadata: False
shuffle: True
shuffle_buffer_size: 1024
feature_norm: True
# dataset_root: "/data/shengzhenli/theia_navsim_datasets"
dataset_root: "/data/shengzhenli/theia_navsim_stitch_datasets"
dataset_ratio: 1.0
load_action: False
